---
- name: copy consul service file
  template:
    src: systemd/consul-agent.service.j2
    dest: /etc/systemd/system/consul-agent.service
  notify: reload systemd daemon

- name: copy consul config
  template:
    src: consul/config.json.j2
    dest: "{{ consul_dir }}/config.json"
  notify: restart consul-agent

- name: enable consul service
  service:
    name: consul-agent
    enabled: true
    state: started
